UrbanDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('platform/', include('task4.urls')),
    path('registration/', include('task5.urls')),
]

task4/urls.py
from django.urls import path
from .views import GamesView, CartView, PlatformView

app_name = 'task4'

urlpatterns = [
    path('', PlatformView.as_view(), name='platform'),
    path('games/', GamesView.as_view(), name='games'),
    path('cart/', CartView.as_view(), name='cart'),
]

task5/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup-django/', views.sign_up_by_django, name='signup_django'),
    path('signup-html/', views.sign_up_by_html, name='signup_html'),
]

task5/models.py
from django.db import models

# Create your models here.

task5/forms.py
from django import forms

class UserRegister(forms.Form):
    username = forms.CharField(
        max_length=30,
        label="Введите логин",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        min_length=8,
        label="Введите пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    repeat_password = forms.CharField(
        min_length=8,
        label="Повторите пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    age = forms.CharField(
        max_length=3,
        label="Введите свой возраст",
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    ) 

example1/views.py
from django.shortcuts import render

# Create your views here.

example2/views.py
from django.shortcuts import render

# Create your views here.

example3/views.py
from django.shortcuts import render

# Create your views here.

task2/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


def function_view(request):
    return render(request, "second_task/func_template.html")

class ClassView(TemplateView):
    template_name = "second_task/class_template.html"

task3/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class GamesView(TemplateView):
    template_name = "third_task/games.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = ['Cyberpunk 2077', 'Elden Ring', 'God of War']
        return context

class CartView(TemplateView):
    template_name = "third_task/cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_items'] = []
        return context


class PlatformView(TemplateView):
    template_name = "third_task/platform.html"

task4/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class GamesView(TemplateView):
    template_name = "fourth_task/games.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = ['Cyberpunk 2077', 'Elden Ring', 'God of War']
        return context

class CartView(TemplateView):
    template_name = "fourth_task/cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_items'] = []
        return context


class PlatformView(TemplateView):
    template_name = "fourth_task/platform.html"

task5/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UserRegister

users = ['admin', 'user1', 'john_doe', 'jane_doe']

def sign_up_by_django(request):
    info = {'form': UserRegister()}
    
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            repeat_password = form.cleaned_data['repeat_password']
            age = int(form.cleaned_data['age'])
            
            if (password == repeat_password 
                and age >= 18 
                and username not in users):
                
                return HttpResponse(f"Приветствуем, {username}!")
            
    return render(request, 'fifth_task/registration_page.html', info)

def sign_up_by_html(request):
    info = {}
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')
        age = int(request.POST.get('age', 0))
        
        if (password == repeat_password 
            and len(password) >= 8 
            and age >= 18 
            and username not in users 
            and len(username) <= 30):
            
            return HttpResponse(f"Приветствуем, {username}!")
            
    return render(request, 'fifth_task/registration_page.html', info)

templates/fifth_task/registration_page.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
</head>
<body>
    <h2>Регистрация</h2>

    {% if form %}
        
        <form method="post">
            
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    {% else %}
    
        <form method="post">

            {% csrf_token %}
            <p>
                <label for="username">Введите логин:</label>
                <input type="text" name="username" id="username" maxlength="30" required>
            </p>
            <p>
                <label for="password">Введите пароль:</label>
                <input type="password" name="password" id="password" minlength="8" required>
            </p>
            <p>
                <label for="repeat_password">Повторите пароль:</label>
                <input type="password" name="repeat_password" id="repeat_password" minlength="8" required>
            </p>
            <p>
                <label for="age">Введите свой возраст:</label>
                <input type="number" name="age" id="age" maxlength="3" required>
            </p>
            <button type="submit">Зарегистрироваться</button>
        </form>
    {% endif %}
</body>
</html>

templates/fourth_task/cart.html
{% extends 'fourth_task/menu.html' %}

{% block pagename %}Корзина{% endblock %}

{% block content %}

    {% if cart_items %}
        <p>Ваши товары:</p>
        <ul>
            {% for item in cart_items %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Ваша корзина пуста</h2>
    {% endif %}
    
{% endblock %}
    

templates/fourth_task/games.html
{% extends 'fourth_task/menu.html' %}

{% block pagename %}Игры{% endblock %}

{% block content %}
    <ul>
        {% for game in products %}
            <li>        
                {{ game }} 
                <button>Купить</button>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/fourth_task/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titlename %}Default Page{% endblock %}</title>
</head>
<body>
    <div>
        <h1>{% block pagename %}Default Page{% endblock %}</h1>
        <ul>
            <li><a href="{% url 'task4:platform' %}">Главная</a></li>
            <li><a href="{% url 'task4:games' %}">Магазин</a></li>
            <li><a href="{% url 'task4:cart' %}">Корзина</a></li>
        </ul>
    </div>

    <div>
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

templates/fourth_task/platform.html
{% extends 'fourth_task/menu.html' %}

{% block pagename %}Главная страница{% endblock %}

{% block content %}
    <p>Добро пожаловать на игровую платформу!</p>
{% endblock %}

templates/second_task/class_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
    <h1>Это шаблон для классового представления</h1>
</body>
</html>

templates/second_task/func_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
    <h1>Это шаблон для функционального представления</h1>
</body>
</html>

templates/third_task/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина</title>
</head>
<body>
    <h1>Корзина</h1>

    {% if cart_items %}
        <p>Ваши товары:</p>
        <ul>
            {% for item in cart_items %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Ваша корзина пуста</h2>
    {% endif %}
    
    <a href="{% url 'platform' %}">
        <button>Вернуться обратно</button>
    </a>
</body>
</html>

templates/third_task/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Игры</title>
</head>
<body>
    <h1>Игры</h1>
    <ul>
        {% for game in products %}
            <li>        
                {{ game }} 
                <button>Купить</button>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'platform' %}">
        <button>Вернуться обратно</button>
    </a>
</body>
</html>

templates/third_task/platform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
</head>
<body>
    <h1>Главная страница</h1>
    <nav>
        <ul>
            <li><a href="{% url 'platform' %}">Главная</a></li>
            <li><a href="{% url 'games' %}">Магазин</a></li>
            <li><a href="{% url 'cart' %}">Корзина</a></li>
        </ul>
    </nav>
</body>
</html>